#!/usr/bin/env bash 

TAQ_JAR=target/scala-2.10/taq_2.10-1.0.jar
INPUT=$1
OUTPUT=$2
BAR=$3

if [ -z $INPUT -o -z $OUTPUT ]; then
	echo "Specify an input and output file."
	exit 1
fi

if [ -z $BAR ]; then
	BAR=60
fi

/opt/spark-1.6.1-bin-hadoop2.6/bin/spark-submit  \
	--master local[2] \
	--packages joda-time:joda-time:2.8.2 \
	--jars $TAQ_JAR \
	$TAQ_JAR "$INPUT" "$OUTPUT" $BAR

